### ISSUE TITLE
Crash on Startup when using GZDoom 4.13.2

### ISSUE THREAD

**Issue by SadCack** [JMartinez2098/MetalOpsPremonitions#9]
I tried to start the mod but it crashed immediately. Here is the log.
OS: Windows 11 (or higher) (NT 10.0) Build 22631
    
GZDoom version g4.13.2
W_Init: Init WADfiles.
adding D:/Games/DRM-Free/Doom/Engines/GZDoom 4.13.2/gzdoom.pk3, 679 lumps
adding D:/Games/DRM-Free/Doom/Engines/GZDoom 4.13.2/game_support.pk3, 3308 lumps
adding ./../../../Source Port Files/Doom Engine/PLUTONIA.WAD, 2984 lumps
adding D:/Games/DRM-Free/Doom/Engines/GZDoom 4.13.2/lights.pk3, 7 lumps
adding D:/Games/DRM-Free/Doom/Engines/GZDoom 4.13.2/brightmaps.pk3, 499 lumps
adding D:/Games/DRM-Free/Doom/Engines/GZDoom 4.13.2/game_widescreen_gfx.pk3, 214 lumps
adding C:/Users/user/Downloads/MetalOpsPremonitions_2.1/MetalOpsPremonitions-main.pk3, 3596 lumps
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device IOpenAL Soft on Speakers (Schiit Modi 3+)
  EFX enabled
I_InitInput
I_StartupMouse
I_StartupKeyboard
I_StartupXInput
I_StartupRawPS2
I_StartupDirectInputJoystick
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon RX 6800 XT
GL_VERSION: 4.6.0 Core Profile Context 24.10.1.241007 (Core profile)
GL_SHADING_LANGUAGE_VERSION: 4.60

Max. texture size: 16384
Max. texture units: 32
Max. varying: 64
Max. combined shader storage blocks: 96
Max. vertex shader storage blocks: 96
Resolution: 2560 x 1440
I_Init: Setting up machine state.
CPU speed: 4104 MHz
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz
  Family 6, Model 165, Stepping 5
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
GScript error, "MetalOpsPremonitions-main.pk3:zscript/weapons/ssg.zs" line 26:
GUnknown identifier 'classicFireMode'
GScript error, "MetalOpsPremonitions-main.pk3:zscript/weapons/ssg.zs" line 31:
GUnknown identifier 'classicFireMode'
GScript error, "MetalOpsPremonitions-main.pk3:zscript/weapons/ssg.zs" line 36:
GUnknown identifier 'classicFireMode'

Execution could not continue.
3 errors while parsing DECORATE scripts

**Comment by JMartinez2098** [comment]
I forgot to remove any references to classicSSGFire, as this was going to be a feature where the SSG would shoot Buckshot like the original SSG. I will fix this in the next version along with ModDB.

**Comment by JMartinez2098** [comment]
Check now, it should be fixed.
